# Generated by Django 5.0.6 on 2025-01-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0013_alter_portfoliomodels_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodels',
            name='cotacao',
            field=models.FloatField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodels',
            name='valor',
            field=models.FloatField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodels',
            name='variacaoAnual',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
