# Generated by Django 5.0.6 on 2025-01-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0014_alter_portfoliomodels_cotacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodels',
            name='valor',
        ),
    ]
