# Generated by Django 5.0.6 on 2025-01-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0015_remove_portfoliomodels_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodels',
            name='dy',
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='dy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
