# Generated by Django 5.0.6 on 2025-01-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0016_remove_portfoliomodels_dy_ativosmodels_dy'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodels',
            name='dy',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
