# Generated by Django 5.0.6 on 2025-01-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0018_remove_portfoliomodels_valuationdy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliomodels',
            old_name='metaDy',
            new_name='metaDividendYield',
        ),
    ]
