# Generated by Django 5.0.6 on 2025-01-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0019_rename_metady_portfoliomodels_metadividendyield'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativosmodels',
            name='debtToEquity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='earningsQuarterlyGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='enterpriseValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='fiftyTwoWeekHigh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='fiftyTwoWeekLow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='freeCashflow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='longBusinessSummary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='pl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='revenueGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='twoHundredDayAverage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
