# Generated by Django 5.0.6 on 2025-01-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0020_ativosmodels_debttoequity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativosmodels',
            name='longBusinessSummary',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
