# Generated by Django 5.0.6 on 2025-01-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0021_alter_ativosmodels_longbusinesssummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodels',
            name='debtToEquity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='earningsQuarterlyGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='enterpriseValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='fiftyTwoWeekHigh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='fiftyTwoWeekLow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='freeCashflow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='pl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='revenueGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='twoHundredDayAverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodels',
            name='dy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
