# Generated by Django 5.0.6 on 2025-01-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0022_portfoliomodels_debttoequity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodels',
            name='longBusinessSummary',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
