# Generated by Django 5.0.6 on 2025-01-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0023_portfoliomodels_longbusinesssummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativosmodels',
            name='balancoPatrimonial',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='capitalStockComposition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='demonstracaoDoFluxoDeCaixa',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='demonstracaoDoResultadoDoExercicio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='freeFloatResult',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='positionShareholders',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='balancoPatrimonial',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='capitalStockComposition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='demonstracaoDoFluxoDeCaixa',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='demonstracaoDoResultadoDoExercicio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='freeFloatResult',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='positionShareholders',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
