# Generated by Django 5.0.6 on 2025-01-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0024_ativosmodels_balancopatrimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativosmodels',
            name='dataFinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativosmodels',
            name='dataInicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='dataFinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliomodels',
            name='dataInicial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
